import pandas as pd
import numpy as np
import pandas_ta as ta

LOOK_FORWARD_CANDLES = 24
PROFIT_TARGET_PCT = 1.0
STOP_LOSS_PCT = 1.0

def create_target_labels(df, look_forward, profit_target_pct, stop_loss_pct):
    """This function is correct and remains unchanged."""
    target = np.zeros(len(df))
    profit_target = 1 + (profit_target_pct / 100)
    stop_loss_target = 1 - (stop_loss_pct / 100)
    
    for i in range(len(df) - look_forward):
        entry_price = df['close'].iloc[i]
        future_window = df.iloc[i + 1: i + 1 + look_forward]

        profit_hit_mask = future_window['high'] >= entry_price * profit_target
        stop_loss_hit_mask = future_window['low'] <= entry_price * stop_loss_target

        first_profit_hit = np.where(profit_hit_mask)[0]
        first_stop_loss_hit = np.where(stop_loss_hit_mask)[0]

        if len(first_profit_hit) > 0 and len(first_stop_loss_hit) > 0:
            target[i] = 1 if first_profit_hit[0] < first_stop_loss_hit[0] else -1
        elif len(first_profit_hit) > 0:
            target[i] = 1
        elif len(first_stop_loss_hit) > 0:
            target[i] = -1
    return target

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply technical indicators and CORRECTED signals to raw OHLCV data.
    The signals now perfectly mirror the backend JavaScript strategies.
    """

    # === Technical Indicators (with additions for new signal logic) ===
    df.ta.rsi(length=14, append=True)
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    df.ta.stoch(k=14, d=3, append=True)
    df.ta.cci(length=20, append=True)
    df.ta.bbands(length=20, std=2, append=True)
    df.ta.atr(length=14, append=True)
    
    # Corrected SMA periods to match backend and added 10-period SMA
    df.ta.sma(length=10, append=True)
    df.ta.sma(length=50, append=True)
    df.ta.psar(append=True)
    
    # Using standard Ichimoku parameters
    df.ta.ichimoku(conversion=9, base=26, span=52, append=True)
    df.ta.obv(append=True)

    # Add SMA of OBV for the OBV crossover strategy
    df['OBV_SMA_20'] = df['OBV'].rolling(window=20).mean()

    # Get the exact column names generated by pandas-ta for clarity
    rsi_col = 'RSI_14'
    macd_col, macd_signal_col = 'MACD_12_26_9', 'MACDs_12_26_9'
    stoch_k_col, stoch_d_col = 'STOCHk_14_3_3', 'STOCHd_14_3_3'
    cci_col = 'CCI_20_0.015'
    bbl_col, bbu_col = 'BBL_20_2.0', 'BBU_20_2.0'
    atr_col = 'ATRr_14' # pandas-ta often appends 'r' for RMA-based ATR
    sma10_col, sma50_col = 'SMA_10', 'SMA_50'
    psar_col = [col for col in df.columns if 'PSAR' in col and 'l' not in col and 's' not in col][0]
    tenkan_col, kijun_col = 'ITS_9', 'IKS_26'
    spanA_col, spanB_col = 'ISA_9', 'ISB_26'
    
    # --- Signals Block: REWRITTEN TO MATCH BACKEND LOGIC ---
    
    # 1. ATR Signal (Volatility Breakout)
    atr_multiplier = 2.0
    prev_close = df['close'].shift(1)
    upper_band = prev_close + (df[atr_col] * atr_multiplier)
    lower_band = prev_close - (df[atr_col] * atr_multiplier)
    buy_cond_atr = df['high'] > upper_band
    sell_cond_atr = df['low'] < lower_band
    df['atr_signal'] = np.select([buy_cond_atr, sell_cond_atr], [1, -1], default=0)

    # 2. Bollinger Bands Signal (Mean Reversion - This one was already correct)
    buy_cond_bb = df['close'] < df[bbl_col]
    sell_cond_bb = df['close'] > df[bbu_col]
    df['bb_signal'] = np.select([buy_cond_bb, sell_cond_bb], [1, -1], default=0)

    # 3. CCI Signal (Mean Reversion Crossover)
    prev_cci = df[cci_col].shift(1)
    buy_cond_cci = (prev_cci < -100) & (df[cci_col] >= -100)
    sell_cond_cci = (prev_cci > 100) & (df[cci_col] <= 100)
    df['cci_signal'] = np.select([buy_cond_cci, sell_cond_cci], [1, -1], default=0)

    # 4. Ichimoku Cloud Signal (Filtered Crossover)
    prev_tenkan, prev_kijun = df[tenkan_col].shift(1), df[kijun_col].shift(1)
    bullish_cross = (prev_tenkan < prev_kijun) & (df[tenkan_col] >= df[kijun_col])
    is_above_cloud = (df['close'] > df[spanA_col]) & (df['close'] > df[spanB_col])
    buy_cond_ichi = bullish_cross & is_above_cloud
    bearish_cross = (prev_tenkan > prev_kijun) & (df[tenkan_col] <= df[kijun_col])
    is_below_cloud = (df['close'] < df[spanA_col]) & (df['close'] < df[spanB_col])
    sell_cond_ichi = bearish_cross & is_below_cloud
    df['ichimoku_signal'] = np.select([buy_cond_ichi, sell_cond_ichi], [1, -1], default=0)

    # 5. MACD Signal (Line Crossover)
    prev_macd, prev_signal = df[macd_col].shift(1), df[macd_signal_col].shift(1)
    buy_cond_macd = (prev_macd < prev_signal) & (df[macd_col] >= df[macd_signal_col])
    sell_cond_macd = (prev_macd > prev_signal) & (df[macd_col] <= df[macd_signal_col])
    df['macd_signal'] = np.select([buy_cond_macd, sell_cond_macd], [1, -1], default=0)

    # 6. OBV Signal (Crossover with its SMA)
    prev_obv, prev_obv_sma = df['OBV'].shift(1), df['OBV_SMA_20'].shift(1)
    buy_cond_obv = (prev_obv < prev_obv_sma) & (df['OBV'] >= df['OBV_SMA_20'])
    sell_cond_obv = (prev_obv > prev_obv_sma) & (df['OBV'] <= df['OBV_SMA_20'])
    df['obv_signal'] = np.select([buy_cond_obv, sell_cond_obv], [1, -1], default=0)

    # 7. Parabolic SAR Signal (Flip Event)
    prev_psar = df[psar_col].shift(1)
    buy_cond_psar = (prev_psar > prev_close) & (df[psar_col] <= df['close'])
    sell_cond_psar = (prev_psar < prev_close) & (df[psar_col] >= df['close'])
    df['psar_signal'] = np.select([buy_cond_psar, sell_cond_psar], [1, -1], default=0)

    # 8. RSI Signal (Mean Reversion Crossover)
    prev_rsi = df[rsi_col].shift(1)
    buy_cond_rsi = (prev_rsi < 30) & (df[rsi_col] >= 30)
    sell_cond_rsi = (prev_rsi > 70) & (df[rsi_col] <= 70)
    df['rsi_signal'] = np.select([buy_cond_rsi, sell_cond_rsi], [1, -1], default=0)

    # 9. SMA Crossover Signal (Event with correct 10/50 periods)
    prev_sma10, prev_sma50 = df[sma10_col].shift(1), df[sma50_col].shift(1)
    buy_cond_sma = (prev_sma10 < prev_sma50) & (df[sma10_col] >= df[sma50_col])
    sell_cond_sma = (prev_sma10 > prev_sma50) & (df[sma10_col] <= df[sma50_col])
    df['sma_crossover_signal'] = np.select([buy_cond_sma, sell_cond_sma], [1, -1], default=0)

    # 10. Stochastic Signal (Filtered Crossover)
    prev_k, prev_d = df[stoch_k_col].shift(1), df[stoch_d_col].shift(1)
    bullish_stoch_cross = (prev_k < prev_d) & (df[stoch_k_col] >= df[stoch_d_col])
    is_oversold = df[stoch_k_col] < 20
    buy_cond_stoch = bullish_stoch_cross & is_oversold
    bearish_stoch_cross = (prev_k > prev_d) & (df[stoch_k_col] <= df[stoch_d_col])
    is_overbought = df[stoch_k_col] > 80
    sell_cond_stoch = bearish_stoch_cross & is_overbought
    df['stoch_signal'] = np.select([buy_cond_stoch, sell_cond_stoch], [1, -1], default=0)
    
    # --- End of Rewritten Signals Block ---
    
    # Combined momentum signal
    signal_columns = [
        'atr_signal','bb_signal','cci_signal','ichimoku_signal',
        'macd_signal','obv_signal','psar_signal','rsi_signal',
        'sma_crossover_signal','stoch_signal'
    ]
    df['momentum_strength'] = df[signal_columns].sum(axis=1)

    # === Target Labels ===
    df['target'] = create_target_labels(df, LOOK_FORWARD_CANDLES, PROFIT_TARGET_PCT, STOP_LOSS_PCT)
    
    # Drop rows with NaNs created by indicators and shift operations
    df = df.dropna().reset_index(drop=True)

    return df
