import os
import sys
from pathlib import Path
from datetime import datetime
import pandas as pd

# 🟢 1. DYNAMIC PATH ALIGNMENT
# This finds ~/Project/ML/ and adds it to the search path
ROOT = Path(__file__).resolve().parents[2] 
sys.path.append(str(ROOT))

def perform_ml_server_audit(candle_list):
    """🔍 Analyzes the data payload generated by the ML Engine."""
    print(f"\n🚀 STARTING NEURAL DATA AUDIT - {datetime.now().strftime('%H:%M:%S')}")
    if not candle_list:
        print("❌ CRITICAL: Payload is empty.")
        return

    seen_times = {}
    duplicate_errors = 0
    sequence_errors = 0

    for i, candle in enumerate(candle_list):
        t = candle.get('time')
        # Check for Duplicates
        if t in seen_times:
            print(f"❌ DUPLICATE: Time {t} at Index {seen_times[t]} and {i}")
            duplicate_errors += 1
        seen_times[t] = i
        # Check for Sequence
        if i > 0 and t <= candle_list[i-1].get('time'):
            print(f"❌ SEQUENCE BREAK: Index {i} ({t}) <= Index {i-1}")
            sequence_errors += 1

    print(f"\n--- 🏁 RESULTS: {duplicate_errors} Duplicates | {sequence_errors} Sequence Breaks ---")

if __name__ == "__main__":
    try:
        # 🟢 2. ATTEMPT PACKAGE IMPORT
        from main4 import ACTIVE_BOTS
        
        if not ACTIVE_BOTS:
            print("\n⚠️  Server is running but NO active bots found.")
            print("💡 Go to your browser, START THE BOT, then run this again.")
        else:
            for user_id, bot_data in ACTIVE_BOTS.items():
                print(f"\n🔍 Auditing Active Session: {user_id}")
                # Use the sanitized data we created in the heartbeat loop
                candles = bot_data.get('last_emitted_candles', []) 
                perform_ml_server_audit(candles)

    except ImportError as e:
        print(f"❌ CRITICAL IMPORT ERROR: {e}")
        print(f"Path searched: {sys.path[-1]}")
